# See https://github.com/marketplace/actions/ftp-deploy
#on: push
#name: ðŸš€ Deploy website on push
#jobs:
#  web-deploy:
#    name: ðŸŽ‰ Deploy
#    runs-on: ubuntu-latest
#    steps:
#    - name: ðŸšš Get latest code
#      uses: actions/checkout@v2
#    
#    - name: ðŸ“‚ Sync files
#      uses: SamKirkland/FTP-Deploy-Action@4.1.0
#      with:
#        server: ftp.samkirkland.com
#       username: myFtpUserName
#       password: ${{ secrets.ftp_password }}